### ISSUE TITLE
Flow Definitions Removed During Compile/Build

### ISSUE THREAD

**Issue by mwalkerwells** [graphql/express-graphql#103]
I'm using Flow in my project & I'd like to use all the flow definitions from express-graphql, yet they are removed during the build script.

Disclaimer: I'm unfamiliar with how Travis CI works.

I know I can manually download the project to get access to the 'src' directory where the definitions are, but that seems a bit weird. I'd like to use npm install to maintain all my packages + preserve the flow type definitions.

What is the best practice for preserving flow definitions using npm install? & is there a way to do so that is not package specific & would apply to all flow typed libraries?

**Comment by mwalkerwells** [comment]
Just found this: https://github.com/flowtype/flow-typed/issues/16

**Comment by ryyppy** [comment]
As of the state right now, there are only two ways to properly consume types from npm packages:

1.  Either Convince the project maintainers to provide a build step to basically recursively copy all `src/` files to `dist/` to the same position as the ES5 files with a `flow.js` suffix (AFAIK draft.js will do this in the future)

2.  Or create and consume a libdef file separately (as currently done in `flow-typed`)


Option 2 will also be required if you try to use an minified browser build of course, since in my knowledge there is no automated way to extract all types into a single file ...

For this project, Option 1 would actually be a good fit

**Comment by mwalkerwells** [comment]
@leebyron Curious if #1 is something you'd consider?

**Comment by leebyron** [comment]
Yes, this is something I think is worth considering, though the graphql package itself should export types in the same fashion first.

It's also worth point out that the Flow team does not encourage libraries export types in this way due to possible breakage when Flow updates.

**Comment by mwalkerwells** [comment]
Ah, interesting—that makes sense.

**Comment by mwalkerwells** [comment]
[Flow v32 Release Notes:](https://github.com/facebook/flow/releases/tag/v0.32.0)

> We're starting work on flow gen-flow-files, which consumes Flow code and outputs .flow files containing only the types exported. It's alpha-level and we're still iterating on it, so use at your own peril!

:)

**Comment by nodkz** [comment]
Yep, incredible synchronous work of Facebook's OSS teams.

![team-work](https://cloud.githubusercontent.com/assets/1946920/18300070/ad09e308-74e7-11e6-9e67-ce98a3b5f8ab.gif)

Lee posted about flow 0.32 in tweeter yesterday.

**Comment by nodkz** [comment]
Also, you may track progress with `graphql-js` here https://github.com/graphql/graphql-js/issues/359

**Comment by mwalkerwells** [comment]
Thanks—& yes, they're OTS.
