### ISSUE TITLE
Broken express etag support

### ISSUE THREAD

**Issue by kretz** [graphql/express-graphql#115]
Hi,

The commit 48e6659945477bd706fe22173f450c16eddd5bf5 broke the built-in etag support of express. 

This is due to using `response.write` instead of `response.send` (which has the etag generation inside) https://github.com/graphql/express-graphql/blob/master/src/index.js#L250.

The commit states that this is made to be compatible with connect. Is there a way to also support etags for express?

Thanks,
Martin

**Comment by brandondoran** [comment]
Since the original issue, the commit https://github.com/graphql/express-graphql/commit/3d5ed8ad784b98258882ce50a7365e552caba37e changed `response.write(data)` and `response.end()` to just `response.end(data)`. But we are still at the problem of no etags. `end` is a method from Node core [ServerResponse](https://nodejs.org/api/http.html#http_response_end_data_encoding_callback). I imagine there is a reason for using that over Express `send` but this breaks content based http caching.

I would be curious to hear the reasoning behind using `end` here.  Is there any chance of a work around to enable etags?

**Comment by lacker** [comment]
Express's etags logic in the `send` function is like 7 lines of code, so perhaps a reasonable workaround would just be adding similar code to `express-graphql`.

https://github.com/expressjs/express/blob/master/lib/response.js#L109

**Comment by kretz** [comment]
Would it be reasonable to use 'send()' only for express? It feels like to
me like the express framework's functionality should be leveraged when it
is there, so as not to confuse developers.

**Comment by lacker** [comment]
Seems reasonable to me. As long as we have tests for both the `connect` behavior that we want and the `express` behavior that we want.
