### ISSUE TITLE
[Question] Does it scale ?

### ISSUE THREAD

**Issue by PCreations** [graphql/express-graphql#168]
I'm actually evaluating if we gonna use it for our project and can't find anywhere some cache strategies between the front-end and the express-graphql server. My express-graphql server fetches REST endpoints (through DataLoader) cached by varnish, with cache invalidation based on unique ids. Question is : can I (and should I) add a varnish between my frontend and the express-graphql server ? We can actually handles thousands of requests with the varnish without poping new servers and I'm afraid we're gonna need to do that with the adition of the node server.

**Comment by sibelius** [comment]
@PCreations please post this question on StackOverflow or on discord or graphql.slack.com

**Comment by wincent** [comment]
Thanks for the question, @PCreations. I agree with @sibelius that you'll get the most valuable answers to this on a venue like StackOverflow etc, so I'm going to close this for now. If you do post a question in one of those places, feel to link to it from a comment here so that others who find this issue can follow.
