### ISSUE TITLE
arg parameters in resolve don't inherit from Object

### ISSUE THREAD

**Issue by pszabop** [graphql/express-graphql#177]
Given a resolve function that looks like

    resolve: (root, args, request) => {
      test =  { uuid: '1234', description: 'lead singer of the Doors' };
      console.log('result: ' + Object.prototype.hasOwnProperty.call(args.person, 'description'));
      // XXX This fails!:  console.log('result: ' + args.person.hasOwnProperty('description'));
      console.log('result: ' + test.hasOwnProperty('description'));
      return db.personUpdate(request.user, args.person);
    }

If I try to use `args.person.hasOwnProperty('description')` I get the error `hasOwnProperty is not a function`.   I'm forced to use `Object.prototype.hasOwnProperty.call` per this [issue in another module](https://github.com/mozilla/nunjucks/issues/468#issuecomment-115026511)

Note that if I create an object similar to args.person I don't get an error.  See the `test` example in the code snippet.

I'm not enough of a javascript guru to say why this is happening, but it is a gotcha for when I"m attempting an update, where I merge the update with the existing object depending on what attributes are set in the update.  My unit tests for the database pass (e.g. just like the `test` object above), but then fails when I attempt have graphql-express use my database.

I've checked, and there is no attribute 'hasOwnProperty' on args.person, per [the Mozilla description of Object.hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)

**Comment by wincent** [comment]
This is happening because [we use](https://github.com/graphql/graphql-js/blob/a72408ee6f456f679b1182787299da21db534584/src/execution/values.js#L116) `Object.create(null)` to initialize the `args` object, and have done since https://github.com/graphql/graphql-js/commit/b93f0490836c75a83e8ae680545756bbcbb6c2bd.

I think the rationale is that [step 1](http://facebook.github.io/graphql/#sec-Coercing-Field-Arguments) of `CoerceArgumentValues` in the GraphQL spec is :

> Let `coercedValues` be an empty unordered Map.

And the closest thing we have in JS to an "empty" object is the kind of prototype-less shell that you create with `Object.create(null)`.

This in turn means that you can probably replace your `args.person.hasOwnProperty('description')` check with `args.person.description !== null` or similar and have almost equivalent semantics:

- `args.person.description === null` would be true when the property is explicitly null.
- `args.person.description === void 0` or `=== undefined` would be true when the property is unset (or diabolically set explicitly to `undefined`).
- `args.person.description == null` would be true when either of the above is true.
- `args.person.description` would be truthy for most other values (`0` and `''` being counterexamples).

I'm going to close this for now, but please comment again if you have any follow-up.

**Comment by nfantone** [comment]
@wincent This is a problem when you pass your coerced objects around as inputs to other libraries/tools and you _don't control_.

This happened to me today when using `dynamo-data-types` to convert GraphQL inputs into DynamoDB representations. The [module uses `obj.hasOwnProperty`](https://github.com/kayomarz/dynamodb-data-types/blob/7e4afb360e8aa61a0812709a8d5e64cbb400f192/lib/AttributeValue.js#L134), which raised an exception. This can happen any time, any where from sources that are out of reach for users. Having to wrap my inputs with ad-hoc objects (`{ ...myGraphQLInput }`) feels hackish and unsafe.

**Comment by IvanGoncharov** [comment]
@nfantone It's general problem of JS you can't use standard objects as maps. For example, if you create an argument called `hasOwnProperty`, `toValueOf`, `toString` or with any other property name derived from `Object`. What will happen to `dynamo-data-types` if it gets object where `hasOwnProperty` is not a function? 

> The module uses obj.hasOwnProperty, which raised an exception.

It should be fixed in `dynamo-data-types` either by using `Object.keys` or `Object.hasOwnProperty.call(obj, key)`.

**Comment by nfantone** [comment]
I'd argue that's not a realistic expectation. "Fixing" all libraries out there is not viable. Not to mention, many library authors could understandably take no action and consider this no be a very valid, correct usage of a native function. 

And my original question still stands: besides debatable semantics, what's the benefit in using `Object.create(null)` for resolving objects?

**Comment by IvanGoncharov** [comment]
> There's a tacit consensus that array[0] = 2 assigns the value 2 to the start of array, just as there is about the existence of very well known, expected attributes on an Object.

@nfantone But it shouldn't affect your schema design you should be able to do this:
```graphql
type Query {
  foo(toLocaleString: Boolean): String
}
```
-------
Actually, it's a question for `graphql-js` and it's already discussed here: https://github.com/graphql/graphql-js/pull/504
And I don't think we would change anything since it's a big breaking change because following is valid at the moment:
```js
for (const key in args) {
  //No need for hasOwnProperty
}
```

**Comment by nfantone** [comment]
@IvanGoncharov Thanks for pointing me to the appropriate issue! Sad to see that it's closed, though.

**Comment by quinten1333** [comment]
No response.... This annoyed me so I made a library to compensate for this weird choice that is faster than going to json and back. Link: https://www.npmjs.com/package/normalize-object-inheritance

I get that you want to adhere to the GraphQL spec as much as possible. However, this library is only useful if it can be integrated in other code and libraries.
