### ISSUE TITLE
How to make Subscription schema ?

### ISSUE THREAD

**Issue by kenshero** [graphql/express-graphql#207]
I try to make subscription. but cannot get it.

Do you have example code for create simple subscription. 

Thank you.

**Comment by wincent** [comment]
Thanks for the question!

Subscriptions aren't officially part of the GraphQL spec yet, so we haven't implemented them in express-graphql. @robzhu is actively working now on an RFC for adding subscriptions, and which will be iterated on out in the open once the initial draft is completed ("soon"™). I believe that some third-party libraries like Apollo have implemented experimental versions of subscriptions, so we'll see how closely they align with the spec by the time it has finished going through the RFC process. But for now, I think I can close this because there's no "official" way to do this in express-graphql at this time.

**Comment by helfer** [comment]
@kenshero For what it's worth, you can try out the subscription implementation we have for [graphql-server](https://github.com/apollographql/graphql-server) by using [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions) and [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws).

Here's a [blog post](https://dev-blog.apollodata.com/graphql-subscriptions-in-apollo-client-9a2457f015fb) we wrote about it a few months ago.

**Comment by devarashetty** [comment]
+ 1

**Comment by jalalat** [comment]
Hi @wincent @robzhu any info when we can get subscription as part of express-graphql.

**Comment by robzhu** [comment]
@jalalat, Assuming you mean an end-to-end working GraphQL Subscriptions system, this is unlikely to become part of express-graphql itself for two reasons:
1) Subscriptions generally requires some way to detect and trigger domain-specific events (most people use a pubsub system for this)
2) Subscriptions requires a persistent, bi-directional transport between the client and server. 

These are both application-specific decisions. We would not want to expand the scope of express-graphql to include all possible integrations/configurations of surrounding systems. 

See @helfer's post above for some ideas on how to add subscription support in production.

**Comment by mishelen** [comment]
Ok, how to teach graphiql to listen additional endpoint for subscriptions?
