### ISSUE TITLE
Pass response as second parameter to function version of graphQLHTTP

### ISSUE THREAD

**Issue by AndrewIngram** [graphql/express-graphql#23]
I'm experimenting with the idea of being able to send non-graphql messages back to the client via custom response headers. The idea is to add the response to the rootValue so that resolve functions in mutations can access it. Then i'd do something like `rootValue.response.setHeader("X-NotificationMessage", "Jolly Good!")`

For this to work, the response needs to be accessible in the advanced function form of `graphQLHTTP`

**Comment by wincent** [comment]
I gather this is related to [your SO question](http://stackoverflow.com/questions/33001632/patterns-for-transient-user-notifications-with-relay), so I'm leaving the link back to it for context.

**Comment by leebyron** [comment]
I would strongly recommend against custom headers and for including this information as part of the response of your GraphQL mutation. 

Perhaps your mutation can have a field called `notificationMessage` which is a string if it needs to report a notification and otherwise is null?

Closing since it looks like you've also gotten attention on SO.
