### ISSUE TITLE
Express-GraphQL Performance metrics in each layer

### ISSUE THREAD

**Issue by sudheerj** [graphql/express-graphql#278]
We are doing performance testing with 50 concurrent users and limit is 200 records.I observed that response time between GraphQL resolver result to server response time is around 150-200ms.There is no business logic or implementation to take more time.This time is very huge and impacting the total response time for the end user.

I tried with both express-graphql and  Apollo servers but there is no difference.Can you please assist how we can figure it out what layer is taking more time and how to optimize it.

Thanks in advance

**Comment by robzhu** [comment]
re: Apollo server, @stubailo might be able to shed some insight on what's happening here and propose alternatives.

**Comment by stubailo** [comment]
Yeah I have heard of cases where [GraphQL.js](https://github.com/graphql/graphql-js) doesn't resolve the promise until much later after the results have been calculated. There isn't anything `express-graphql` or `graphql-server` can do about it though, I think it's an issue in the core package. I haven't seen a concrete reproduction yet though. Can you put together the minimal server that exhibits this behavior? That will be much easier to work with to find the underlying cause.

**Comment by asiandrummer** [comment]
@sudheerj Closing this one due to inactivity, but if you do put together a working server implementation that reproduces this issue, please feel free to reopen this issue/open another issue in `graphql-js` repo. We're curious to know what's causing this delay people have been seeing and would love to collaborate to optimize the performance.

Thanks for the report!
