### ISSUE TITLE
How to do live-reload

### ISSUE THREAD

**Issue by nsisodiya** [graphql/express-graphql#296]
I have a graphql based node application. I am using express-graphql.
How to enable live-reload. I want, whenever there is a change, graphiql should live-reload.

**Comment by nsisodiya** [comment]
is it possible to add something like
```js
app.use('/graphql', graphqlHTTP({
  schema: MyGraphQLSchema,
  graphiql: true,
  livereload: true
}));
```

**Comment by wincent** [comment]
Assuming that when you say "whenever there is a change, graphiql should live-reload", you are referring to a change in the data on the server, no, that's not currently possible @nsisodiya, but it's a good question.

In terms of live updates:

* Subscriptions are currently in RFC and soon to be added to the GraphQL spec (via [this PR](https://github.com/facebook/graphql/pull/305)). See [the original RFC PR](https://github.com/facebook/graphql/pull/267) and related issues for a bunch of discussion on that.
* You'll see on those links a bunch of related discussion around a related concept which we're calling "live queries", but which are not yet in the spec nor do they exist as a formal RFC.
* People have hacked together demos showing subscriptions working in GraphiQL: for example, see [GraphiQL-Subscriptions-Fetcher](https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher). Apollo has also done work on making their `graphql-server` package [support websockets](https://github.com/apollographql/graphql-server/pull/308). Likewise, @robzhu's [React Conf talk](https://youtu.be/AYbVMNtO-ro?t=14m35s) shows a demo in GraphiQL, but note that this was bolted on for demonstration purposes around the time the RFC was being prepared, so it does not contain production ready or released code.

**Comment by wincent** [comment]
Whoops, didn't mean to hit close on that. Please feel free to comment further if you have any clarifications or questions.

**Comment by nsisodiya** [comment]
What I mean to say, "when I make changes in File, graphiql tab should auto-reload".
I am NOT talking about reload when Data-Changes.

**Comment by nsisodiya** [comment]
@wincent - Please re-open bug.

**Comment by wincent** [comment]
Can you clarify what kind of files you are making changes in? Do you mean files related to the schema (`MyGraphQLSchema` in your example)?

**Comment by wincent** [comment]
If so, check out [this](https://github.com/relayjs/relay-starter-kit/pull/67/files) for one example of how this was done.

**Comment by nsisodiya** [comment]
@wincent Basically, when JavaScript files changes, `nodemon` restart my node app. when this restart happen, I want a reload page/tab of graphiql.

**Comment by nsisodiya** [comment]
@wincent I went to the link, That code, restart graphql server. I want, when server restart, client page (graphiql) should reload.

**Comment by asiandrummer** [comment]
@nsisodiya reloading a client-side application (webpage in this case) when the server restarts sounds like a good "feature request" to me, but I'm not sure if we want to support it in this repo because:
1. `express-graphql`'s main purpose as I understand is to provide a thin easy-to-use endpoint in the format of express middleware, and in my personal opinion live-reloading constitutes as a nice-to-have feature rather than a must-have.
2. There are some mini libraries that seem to already support your need. [Take a look at this repo for instance](https://www.npmjs.com/package/reload) - I pulled this from the quick Google search, so there might be a better alternative.

My recommendation to resolve your use case is to create a custom middleware in your server code, implement a live-reloading step in your custom middleware, and [combine with this middleware](https://github.com/graphql/express-graphql#combining-with-other-express-middleware) to achieve your goal. In the future we may consider incorporating this option - we would love to consider and review any PRs should you choose to experiment with this idea and contribute.

Thanks for the question!
