### ISSUE TITLE
Replace JSON.stringify with fast-json-stringify

### ISSUE THREAD

**Issue by gajus** [graphql/express-graphql#339]
https://github.com/fastify/fast-json-stringify

**Comment by asiandrummer** [comment]
@gajus I'm willing to take a look if someone wants to contribute here, although I'm not sure the benefit of faster stringify-ing outweighs adding another dependency to this lib.

**Comment by asiandrummer** [comment]
Also, apologies for this but that benchmark results is ineligible to me - looks like the use case with short strings has a definite gain. Our prime use case is for objects, and I see ~2x performance gain.

Note that we `JSON.stringify` things only in GraphiQL (correct me if I'm wrong please), and I'd say there is not really a clear advantage for including this library in `express-graphql` since the query/variable object sizes should not matter much if you're experiencing performance issues.

Still a pretty cool lib tho

**Comment by gajus** [comment]
> Note that we JSON.stringify things only in GraphiQL

Which library is responsible for the graphql JSON output?

**Comment by asiandrummer** [comment]
> Which library is responsible for the graphql JSON output?

Queries are executed using`graphql-js` library (reference implementation).
I'm going to close this since it still doesn't seem to add much value to this library, but please reopen if I can be proven otherwise. Thanks for the suggestion by the way @gajus!
