### ISSUE TITLE
Content-Type: application/graphql not support json format ?

### ISSUE THREAD

**Issue by kenshero** [graphql/express-graphql#357]
it work if basic format like this.
createPost(
      topic : "xxxx"
)

but have array object field so fail
createPost(
      topic : "addasdasda",
      image: [{ "name" : "xxxxx.jpg" }]
)

i see the problem is "doble quote"  it should {name : "xxxx.jpg"}.

Can you help me ? Or i need modify field .

**Comment by asiandrummer** [comment]
@kenshero That's because `application/graphql` content type does not expect JSON but a GraphQL query to parse. Your contents need to adhere to [the GraphQL specification, especially around arguments and how they should be written](http://facebook.github.io/graphql/#sec-Language.Arguments). Argument expects a `Name` token, which has [this parse rule](http://facebook.github.io/graphql/#Name).

Also look at [the test suite](https://github.com/graphql/express-graphql/blob/master/src/__tests__/http-test.js) - search for `application/graphql` to see the specific tests for this content header - to see the examples as to how to use it please.
