### ISSUE TITLE
Server Session keep refreshing

### ISSUE THREAD

**Issue by spyalert01** [graphql/express-graphql#39]
I am not sure if this is a bug. 
At the GraphQL

new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve(parentValue, _, { rootValue: { session } }) {
        // use `session` here
      }
    }
  }
});
I am able to see the session the ID and variables value that I set.
But when I press F5(Refresh), the session ID got refreshed, and the variables values become undefined.
My understanding for server session is, the session will keep alive as long as it is not yet expired. Also, it will be staying as long as we didn't Close the browser. 
The case that I am seeing now, is even if I click a link or refresh, the sessionID is already renewed to a new ID, and the value that I previously set for the session variable become undefiend.

Is my understanding on the server session is wrong? or there is a bug on this?

Thanks.

**Comment by bfwg** [comment]
I got the same problem, the session data is undefined.

**Comment by leebyron** [comment]
It's unclear how to answer your question without more information about how you are using express, and likely this issue is not one for this library, but for express.

express-graphql does not have any concept of a session, it's purely a middleware that allows you to run graphql queries at a path in your express server. You will need to use some other library to provide something like a session using whatever technique is appropriate for your application (for example, cookies).

In the README you can see the most simple example of doing this: https://github.com/graphql/express-graphql#advanced-options

If you're using `express-session` like that example illustrates and are having issues, you should investigate further at https://github.com/expressjs/session
