### ISSUE TITLE
Wrong HTTP status code on error

### ISSUE THREAD

**Issue by scarabsoft** [graphql/express-graphql#414]
Hi there,

I discovered an error in version 0.6.11.

```
11:17:28.896 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"errors":[{"message":"Request failed with status code 404","locations":[{"line":1,"column":2}],"path":["filing"]}],"data":{"filing":null}}"
11:17:28.906 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
```
The message says something of status code 404 but the http header is still 200. I guess this is a problem of express-graphql and not a problem of graphql itself, right?

**Comment by IvanGoncharov** [comment]
@scarabsoft `errors` array contains errors generated either by validations or by exceptions in your code. I suspect you are using some kind of proxy requests (schema-stitching, proxy REST API, etc.) and one of them throws `404`.

**Comment by scarabsoft** [comment]
Yes, you are right. It's an failing axios request.

`        resolve(parentValue, args){
                return api.fetchFiling(args.accessionNumber)
            }`

The promise gets rejected and I expect to get a 404 from the service and not a 200 or at least something >= 400. But I see, you guys already had some discussion about this topic.

**Comment by IvanGoncharov** [comment]
> The promise gets rejected and I expect to get a 404 from the service and not a 200 or at least something >= 400.

It's only partial error since you can have both valid data and errors in your response so using 200 is perfectly reasonable.

**Comment by chico-eevee** [comment]
> It's only partial error since you can have both valid data and errors in your response so using 200 is perfectly reasonable.

well that's not true...When you're throwing a `4xx` error you're saying "the client made a mistake, try again" (*not* "the service fell over"). That _should_, rightly, have a description of how the client can fix their next request. Just because you contain a payload describing the reasons for the mistake, doesn't change the fact that it was a _4xx: Client mistake_; it doesn't change the result to _2xx: Service successfully processed your intent_.
