### ISSUE TITLE
Is this project still maintaned?

### ISSUE THREAD

**Issue by AjaxSolutions** [graphql/express-graphql#480]
I'm asking because the last commit was 6 months ago.

**Comment by IvanGoncharov** [comment]
@AjaxSolutions It's a complex question.
I have commit rights and merge bugfixes and improvements.
At the same time I pretty busy with maintaining `graphql-js` and our own projects (`APIs-guru/*`) so I can't dedicate a lot of time to this project.
Also, I don't have NPM rights so I depend on FB guys for doing releases.

AFAIK, ownership of GraphQL projects is moving from FB to the newly created GraphQL Foundation (part of Linux Foundation) so I think they should decide what to do with this project. 

P.S. Since GraphQL Foundation officially formed just a few weeks ago I suspect it will take a few months before we will hear from them.

**Comment by IvanGoncharov** [comment]
I finally got NPM keys for this package so I can work on a new release.
Can't promise active development but I will try to keep it up to date and merge PRs.


------------- 
I'm working on this and other graphql projects in my free time so if you want to support this work please, nominate me for GithHub sponsorship ❤️  http://github.co/2IHdeOw
