### ISSUE TITLE
Intercepting graphiQL requests

### ISSUE THREAD

**Issue by jontonsoup** [graphql/express-graphql#49]
I have a fully stateless backend (token only). Using graphIQL doesn't work because I have no way to pass in my token.

Is there a way to intercept my incoming graphiQL tokens so I can add the token?

**Comment by leebyron** [comment]
As long as that token is read from GET params, then yes. You simply add it as a GET param in the request to graphiql as well.

The idea with the GraphiQL integration is that any GET request to a GraphQL endpoint should also work as a view into GraphiQL by sending the `Accept: application/html` header that all browsers send.

Try: `http://yourserver.com/graphql?token=yourtokenhere&q={__typename}`

If this doesn't work for you because your token must be sent via POST params, then you'll need to provide a custom version of GraphiQL. That's not too hard, recycle as much of https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js as you want, adding the POST details to the `fetcher` and expose it via a different path in your `express` app.

**Comment by jontonsoup** [comment]
Makes sense. Thanks!

Best,

Jon

On Thu, Mar 10, 2016 at 11:40 PM Lee Byron

<
mailto:Lee Byron <notifications@github.com>
> wrote:

As long as that token is read from GET params, then yes. You simply add it as a GET param in the request to graphiql as well.

The idea with the GraphiQL integration is that any GET request to a GraphQL endpoint should also work as a view into GraphiQL by sending the

Accept: application/html

header that all browsers send.

Try:

http://yourserver.com/graphql?token=yourtokenhere&q={__typename}

If this doesn't work for you because your token must be sent via POST params, then you'll need to provide a custom version of GraphiQL. That's not too hard, recycle as much of
https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js
as you want, adding the POST details to the

fetcher

and expose it via a different path in your

express

app.
