### ISSUE TITLE
resolvers argument mixed up

### ISSUE THREAD

**Issue by Sufiane-Souissi** [graphql/express-graphql#562]
I'm trying to setup a little GraphQL server, when trying to pass some value to my *context* object, it get passed to the *args* object.

for example:
```javascript
const root = {
    get(something: String!): (root, args, context, info) => {
   // ... 
   }
}

app.use(
		'/graphql',
		expressGraphql({
			schema,
			rootValue: root,
			graphiql: true,
			context: {
                            "mySuperProperty": "tada"
			},
		}),
	)
```

"mySuperProperty" is not found in the resolver's *context* object but inside the *args* object.
Everything seems shifted (as *info* is undefined, and *root* get the *something* argument)

I'm surely missing something or doing something wrong... :( 

What am I missing ?

thanks for your help !

**Comment by Sufiane-Souissi** [comment]
Just found an issue stackoverflow about the same problem, (w/o answer though)
https://stackoverflow.com/questions/51779230/parameters-ordering-to-get-context-in-express-graphql

**Comment by IvanGoncharov** [comment]
@Sufiane-Souissi It's a very popular question and we need to address it in README.
The short answer: you get the root object as `this` because resolver is called on this object.

> This doesn't match the documentation

We actually have two types of resolvers:
1. specified in `GraphQLObjectType` fields and they get `(parent, args, context, info)`
2. resolvers specified on `parent` itself, in this case, their prototype is `(args, context, info)` and you can access parent using `this`.

**Comment by Sufiane-Souissi** [comment]
Thank you for your answer ! I was able to keep working with *graphql-tools* 
I'll look more into it ! 
Thanks for your help @IvanGoncharov !

**Comment by ZergRushJoe** [comment]
this. does not work with arrow function. why change form the spec?
