### ISSUE TITLE
Best way for split schema into different modules?

### ISSUE THREAD

**Issue by pouyajabbarisani** [graphql/express-graphql#597]
Hi, I'm new to QraphQL and I found some best practices for module system in apollo-server but I can't find anything for express-graphql!

I'm using GraphQLSchema instead of buildSchema. and when I'm trying to split my code into different modules, it will sticks in NodeJs circular dependencies error (returns empty object).

As a GraphQL expert, which one do you recommend? GraphQLSchema or buildSchema?

and also what is the best way for splitting my code for every one of these methods?

**Comment by yanickrochon** [comment]
Take a look at [`merge-graphql-schemas`](https://github.com/Urigo/merge-graphql-schemas)

**Comment by danielrearden** [comment]
The `fields` option provided to the `GraphQLObjectType` and `GraphQLInputObjectType` constructors can be a plain object that maps each field name to its respective configuration, but it can also be a function that returns this object. So instead of doing this

```
new GraphQLObjectType({
  name: "A",
  fields: {
    b: {
      type: B,
    },
  },
});
```

you can do this

```
new GraphQLObjectType({
  name: "A",
  fields: () => ({
    b: {
      type: B,
    },
  }),
});
```

Depending on your project structure, that may be enough to fix the circular dependencies. However, it's also possible to move the relevant require calls inside the function to ensure the modules are only resolved once the function is called, which doesn't happen until the schema object is actually constructed:

```
new GraphQLObjectType({
  name: "A",
  fields: () => {
    const { B } = require("./b");

    return {
      b: {
        type: B,
      },
    };
  },
});
```

If you have additional questions, Stack Overflow is a great resource that may already have the answers you're looking for. Check out [these links](https://graphql.org/community/) for additional community resources as well.
