### ISSUE TITLE
Future plans for this repository

### ISSUE THREAD

**Issue by calebmer** [graphql/express-graphql#75]
What is the roadmap/future plans for this repository? I'm working on a GraphQL HTTP server and I'm evaluating whether I should use this project or build my own. I am a little confused on whether this repository is supposed to be a reference implementation for GraphQL HTTP server authors or is this supposed to be *the* resource for building production grade HTTP GraphQL servers with GraphQL JS. If it is not the latter I ask if that might be reconsidered.

There are a few features which I would like to see before using this in production (in order of importance):

- Remove the `express` dependency. This module could easily be just a connect-style middleware which could then work with `express`, `connect`, `router`, and `koa` (off the top of my head). This might warrant a module name change to `graphql-http` or something.
- Query cache for production. These queries would be pre-parsed/pre-validated and they would be referenced using their operation name by a client.
- By default add an extra validation rule to prevent malicious queries (could be implemented in another module and imported).

These are things I would be willing to contribute (as I would be building them on my own anyway…). If I get approval from the current core team I can start developing these things. I would rather contribute to this repository over creating a new one or keeping the code close sourced.

**Comment by leebyron** [comment]
> is supposed to be a reference implementation for GraphQL HTTP server authors or is this supposed to be the resource for building production grade HTTP GraphQL servers with GraphQL JS.

Definitely yes to the first. This is a reference implementation of how a GraphQL HTTP server should operate, that is the primary goal.

Usually yes to the second, but deferring to the primary goal of being a reference implementation should a change trade-off between the two.

If you're building a node service with graphql-js, then this service should enable your production traffic in the large majority of cases.

**Comment by leebyron** [comment]
> Remove the express dependency. This module could easily be just a connect-style middleware which could then work with express, connect, router, and koa (off the top of my head). This might warrant a module name change to graphql-http or something.

I like this. I think this was just short-sighted on my own part, since I didn't realize these server modules all shared the same middleware API. This should probably be called `graphql-http-middleware` or something like that. Removing the peer-dep for express seems totally acceptable.

> Query cache for production. These queries would be pre-parsed/pre-validated and they would be referenced using their operation name by a client.

@alangenfeld has been thinking about how to add that to this repo in a way that is generic to how you actually want to cache those things. Once we have that we should include examples of how to use it.

> By default add an extra validation rule to prevent malicious queries (could be implemented in another module and imported).

I don't agree with this one because there's an open question as to what qualifies as a malicious query and there are many strategies for dealing with it. I do think having a clear example of how to use the extra `validationRules` option for providing a malicious query checker would be valuable though.

**Comment by leebyron** [comment]
Closing this issue, but feel free to keep discussion up here.
