### ISSUE TITLE
GraphQL Mutation returns 404 outside of graphiql. May have to do with express-graphql

### ISSUE THREAD

**Issue by kennetpostigo** [graphql/express-graphql#88]
I recently worked on a mutation, tested it out in graphiql and it checked out. However when attempting to hook it up the a frontend application it fails. I made a [SoF](http://stackoverflow.com/questions/37278775/graphql-mutation-works-in-graphiql-fails-in-application) post about this, not sure if it is express-graphql. The error at hand is that on this particular mutation for some reason the response payload is "Cannot POST /" along with a 404 code. If you happen to know what may be causing this please comment.

**Comment by jeanpaulversace** [comment]
@kennetpostigo How did you solve this? I'm getting a similar error.

**Comment by mouhsinelonly** [comment]
same thing here ,why does this happen ?

**Comment by quinlanj** [comment]
@jeanpaulversace @mouhsinelonly I had a similar setup. The problem was that my server would not route to the graphql schema unless the HTTP header `Content-Type:application/json` was present, and the body needed to have a valid JSON with the `query` key in it. 

My server uses graphql-server-koa, version 1.2.0.
