### ISSUE TITLE
Example with multer

### ISSUE THREAD

**Issue by gyzerok** [graphql/express-graphql#9]
Can you provide an example how to use this middleware with multer?

I do not understand how to correctly handle file uploads.

**Comment by philostler** [comment]
+1

**Comment by xpepermint** [comment]
+1

**Comment by murz** [comment]
I just took a shot at wiring this up, so I'll share what I came up with and maybe @leebyron can comment on how to approach this in a more idiomatic way (I'm very new to GraphQL)

First I created a GraphQLFile type to represent the files in my mutations. This type just has the shape of the file object produced by multer:
```js
GraphQLFile = new GraphQLInputObjectType({
    name: 'File',
    description: 'A file uploaded via multipart/form-data',
    fields: () => ({
      fieldname: {
        type: new GraphQLNonNull(GraphQLString),
        description: 'The fieldname used to POST this file.',
      },
      originalname: {
        type: new GraphQLNonNull(GraphQLString),
        description: 'The original file name.',
      },
      buffer: {
        type: new GraphQLNonNull(GraphQLBuffer),
        description: 'The file buffered in memory',
      },
...
```

Then I had to pull in the `any-file` branch of multer (until this PR is merged: https://github.com/expressjs/multer/pull/229), which allowed me to create a multer middleware that accepts any field name. The one express-graphql [test using multer](https://github.com/graphql/express-graphql/blob/master/src/__tests__/http-test.js#L461) just uses `.single('file')`, but that is too limited to support uploads for my entire schema because not all of my file fields are named `file` and some mutations contain more than one file. But on the `any-file` branch of multer you can use `.any()` to instruct multer to cast a wider net, and then use a custom `fileFilter` function to reject any fieldnames that don't appear in your schema as GraphQLFile inputs. So my configuration of multer looks something like this (where validFileFieldnames is derived by inspecting my schema):
```js
multer({
  storage: multer.memoryStorage(),
  fileFilter: (req, file, cb) => cb(null, !!validFileFieldnames.find(f => f === file.fieldname)),
}).any();
```

The next missing piece was moving the file objects from where multer puts them to where express-graphql expects them to be. To do that, I wrapped the multer middleware in my own middleware that parses req.body.variables and moves the files onto req.body.variables.input, which looks something like this:
```js
(req, res, next) => {
  multerMiddleware(req, res, () => {
    if (!req.files || req.files.length === 0) {
      next();
      return;
    }
    // Parse variables so we can add to them. (express-graphql won't parse them again once populated)
    req.body.variables = JSON.parse(req.body.variables);
    req.files.forEach(file => {
      req.body.variables.input[file.fieldname] = file;
    });
    next();
  });
};
```

On the clientside I generate forms with validation wired up based on my schema, so for the `GraphQLFile` inputs I just render a file upload field. In my Relay mutations the files are included in the `getFiles` method as shown here: https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getfiles-example and after being sent to the server and buffered by multer I am able to access the files in `mutateAndGetPayload` just like any other field:
```js
const GraphQLAddWidgetMutation = mutationWithClientMutationId({
  name: 'AddWidget',
  inputFields: {
    name: {type: new GraphQLNonNull(GraphQLString)},
    widgetPhoto: {type: new GraphQLNonNull(GraphQLFile)},
  },
  mutateAndGetPayload: ({name, widgetPhoto}) => {
    console.log(widgetPhoto); // { originalname: 'MyPhoto.jpeg', buffer: <Buffer ...
```

**Comment by leebyron** [comment]
There is an example of this in express-graphql's tests:

https://github.com/graphql/express-graphql/blob/master/src/__tests__/http-test.js#L461

Generally I suggest including a reference to the request body in the "rootValue" provided to graphql such that any field resolutions which need to access the uploaded files.

I think @murz's approach is also quite clever.

**Comment by leebyron** [comment]
I expanded on the example in the test along with more comments and link to it from the README

**Comment by nickretallack** [comment]
How would you express this mutation using the mutationWithClientMutationId from graphql-relay-js?

**Comment by nickretallack** [comment]
Hm.  I added multer but I'm still getting the error "Must provide query string." from graphql-express when I try to do a multipart request...

**Comment by nickretallack** [comment]
Oh, my bad.  I have to make sure that middleware comes first.

**Comment by johnconley** [comment]
@nickretallack Would you mind explaining how you got the mutation to work using mutationWithClientMutationId?

**Comment by jkettmann** [comment]
If anyone has problems with this topic: I made an example [repo](https://github.com/jkettmann/relay-authentication) basically for authentication with Relay and GraphQL but it also contains an image upload based on murz's answer.

**Comment by hassaaneforte** [comment]
can someone please guide me about the types, controllers and mutation for uploading a picture though GraphQL

**Comment by danielrearden** [comment]
@hassaaneforte There's several examples above. You may also find it helpful to just use [graphql-upload](https://github.com/jaydenseric/graphql-upload). It [works with express-graphql](https://github.com/jaydenseric/graphql-upload#function-graphqluploadexpress) and provides an Upload scalar for you. See the docs for more details.
